---
# tasks file for /etc/ansible/roles/nginx
- name: Install and configure nginx for static website hosting + letsencrypt(cerbot) SSL certificate.
  hosts: all
  become: yes

  tasks:
    - name: Add epel-release repo
      yum:
       name: epel-release
       state: present

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: Install cerbot
      yum:
       name: python3-certbot-nginx
       state: latest
