---

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install postfix
  yum:
    name: postfix
    state: present

- name: Ensure postfix is running
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: Add configuration main.cf and master.cf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: '../templates/main.cf.j2', dest: '/etc/postfix/main.cf' }
    - { src: '../templates/master.cf.j2', dest: '/etc/postfix/master.cf' } 
    - { src: '../templates/transport.j2', dest: '/etc/postfix/transport'}   

# - name: Copy python script with owner and permissions
#   copy:
#     src: '{{item}}'
#     dest: '/etc/postfix'
#     owner: postfix
#     group: postfix
#     mode: 0644
#   loop:
#     - transport
#     - transport.db

-  name: Copy python script with owner and permissions
   copy:
     src: 'mailtojson.py'
     dest: '/usr/share/nginx'
     owner: nginx
     group: nginx
     mode: 0644


