---

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install postfix
  yum:
    name: postfix
    state: present

- name: Add configuration main.cf and master.cf , transport and virtual
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: postfix
    owner: postfix
  loop:
    - { src: '../templates/main.cf.j2', dest: '/etc/postfix/main.cf' }
    - { src: '../templates/master.cf.j2', dest: '/etc/postfix/master.cf' } 
    - { src: '../templates/transport.j2', dest: '/etc/postfix/transport'}  
    - { src: '../templates/virtual.j2', dest: '/etc/postfix/virtual'} 

- name: run postmap for transport and virtual.
  command: echo "this task will create transport and virtual db"
  notify: 
    - 'run postmap transport'
    - 'run postmap virtual'

-  name: Copy python script with owner and permissions
   copy:
     src: 'mailtojson.py'
     dest: '/usr/share/nginx'
     owner: nginx
     group: nginx
     mode: 0644

-  name: Give insecure permissions to an existing file
   file:
     path: /etc/postfix
     owner: postfix
     group: postfix
     mode: '1777'


- name: Ensure postfix is running
  systemd:
    name: postfix
    state: started
    enabled: yes

