---
# tasks file for /etc/ansible/roles/almalinux
- name: permit traffic in default zone for smtp service
  ansible.posix.firewalld:
    service: smtp
    permanent: true
    state: enabled

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: Disabling SELinux
  selinux:
    state: disabled
  register: selinuxdisabled

# - name: Unconditionally reboot the machine with all defaults
#   ansible.builtin.reboot:
#   when: selinuxdisabled is changed

- name: launch the reboot
  reboot: 
    msg: "Reboot with ansible..."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: selinuxdisabled

 
